### ISSUE TITLE
Outdated Gerber File?

### ISSUE THREAD

**Issue by yinshanyang** [climbalima/split-pcb-throughole#1]
Hi there,

Made a run of PCBs using the gerber files, and found that there were some issues with the connections. Namely on pins 3 and 8.

For pin 3, it seems that for a serial connection to the slave controller, it should be connected to pin 3, the current gerber files connect the TRRS connector to pin 4.

For pin 8, it seems like it is not connected to any of the rows, though my inference is that it should be connected to the second row of keys.

I made these hardware hacks and my keyboard works.

![img_1224](https://cloud.githubusercontent.com/assets/499829/19636852/5f9b3aae-99fe-11e6-8ff1-0e0b529077f0.JPG)

**Comment by climbalima** [comment]
They have been fixed as of now. Sorry I did not see this issue earlier
